config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, path: 'da-vinci/sessions', controllers: {
      sessions: 'admin_users/sessions'
  }

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  authenticate :admin_user do
    namespace 'admin', path: 'da-vinci' do
      resources :admin_users
      resources :users
      resources :omdb_items
      resources :polls

      root to: "omdb_items#index"
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :api do
    get 'search/index'
    get 'search/item'
  end

  resources :movies
  authenticate :user do
    resources :movies do
      resources :polls, on: :member
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @photosArray = OmdbItem.all.map(&:poster_url)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.slim
.m-wrapper
  - 5.times do
    - @photosArray.shuffle.each do |item|
      = image_tag(url_for(item))
.container.container-welcome.pt-0
  .col-sm-12.col-lg-8.offset-lg-2.align-middle style='margin-top: 50vh;transform: translateY(-50%);'
    .row.d-flex.justify-content-center
      h2 'Welcome to Movicorn'
    .row.d-flex.justify-content-center
      em The website to find when your favorite film will be available
    .row.d-flex.justify-content-center
      .col-sm-8.col-sm-offset-2.col-md-10.col-md-offset-1.col-lg-6.col-lg-offset-3.text-center style='height:auto'
        #imaginary_container
          = form_tag(api_search_item_path, method: 'get') do
            .input-group
              = text_field_tag :query, nil, placeholder: 'Titre du film', class: 'form-control', required: true
              .input-group-addon
                = submit_tag 'Rechercher', class: 'btn btn-submit btn-secondary'
    .row.d-flex.justify-content-center
      hr
    .row.d-flex.justify-content-center style="color: #C0C0C0"
      .card.p-2
        h3 But du projet
        .card-body
          p
            = raw "Ce projet est une <u>preuve de concept</u> et a pour but de mettre en avant la lenteur de la <strong style='color:#29b6f6'>chronologie des médias</strong> en donnant la parole au public."
          p
            = 'Choses à savoir:'
          ul
            li = 'Ce projet est à but non commercial ni lucratif'
            li
              = raw "Les oeuvres présentées ici ne servent que d'illustration et n'appartiennent pas au projet, pour toute réclamation "
              = link_to 'Contactez-moi' , 'mailto:contact@tiboreno.dev'
            li = "Ce projet est basé sur l'API OMDB"