config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, path: 'da-vinci/sessions', controllers: {
      sessions: 'admin_users/sessions'
  }

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  authenticate :admin_user do
    namespace 'admin', path: 'da-vinci' do
      resources :admin_users
      resources :users
      resources :omdb_items
      resources :polls

      root to: "omdb_items#index"
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  namespace :api do
    get 'search/index'
    get 'search/item'
  end

  resources :movies
  authenticate :user do
    resources :movies do
      resources :polls, on: :member
    end
  end
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user
  belongs_to :omdb_item

  validates_presence_of :user, :omdb_item

  NOTE_RANGE = 1..5

  validates :note, :inclusion => { :in => NOTE_RANGE }
end

app/controllers/admin/polls_controller.rb
module Admin
  class PollsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Poll.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Poll.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_movie
  before_action :set_movies_poll, only: [:show, :edit, :update, :destroy]

  # GET /movies/polls
  # GET /movies/polls.json
  def index
    @movies_polls = Poll.all
  end

  # GET /movies/polls/1
  # GET /movies/polls/1.json
  def show
  end

  # GET /movies/polls/new
  def new
    @movie_poll = Poll.new(omdb_item: @movie, user: current_user)
  end

  # GET /movies/polls/1/edit
  def edit
  end

  # POST /movies/polls
  # POST /movies/polls.json
  def create
    @movies_poll = Poll.new(movies_poll_params)
    puts @movies_poll
    respond_to do |format|
      if @movies_poll.save
        format.html { redirect_to movie_polls_path(@movie), notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: movie_polls_path(@movie) }
      else
        format.html do
          flash[:error] = @movies_poll.errors.messages
          puts @movies_poll.errors.messages
          redirect_to new_movie_poll_path(@movie)
        end
        format.json { render json: @movies_poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/polls/1
  # PATCH/PUT /movies/polls/1.json
  def update
    respond_to do |format|
      if @movies_poll.update(movies_poll_params)
        format.html { redirect_to @movies_poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @movies_poll }
      else
        format.html { render :edit }
        format.json { render json: @movies_poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/polls/1
  # DELETE /movies/polls/1.json
  def destroy
    @movies_poll.destroy
    respond_to do |format|
      format.html { redirect_to movies_polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_movie
      @movie = OmdbItem.find(params.dig(:movie_id))
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_movies_poll
      @movies_poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movies_poll_params
      params.require(:poll).permit(:omdb_item, :user,:omdb_item_id, :user_id, :note, :comment)
    end
end

app/views/polls/_form.html.slim
-#frozen_string_literal: true
p.text-center
  = raw t('.new_movie_poll_for_user', movie_title: @movie.title, pseudo: current_user.pseudo)
  = simple_form_for(@movie_poll, url: movie_polls_path(@movie)) do |f|
    = flash[:error]
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
    = f.input :omdb_item_id, type: :hidden, value: @movie.id
    = f.input :user_id, type: :hidden, value: current_user.id
    .form-inputs
      label.mr-2 = t('.note')
      - collection = Poll::NOTE_RANGE.map{|n| [n, t("activerecord.attributes.poll.notes.#{I18n.with_locale(:en) {n.to_words }}")]}
      /= debug collection
      = f.collection_radio_buttons :note, collection, :first, :last do |b|
        = b.radio_button + b.label(class: 'mx-2')
      end
      = f.input :comment
    .form-actions
      = f.button :submit, t('.submit'), class: 'btn btn-primary'

app/views/polls/edit.html.haml
%h1 Editing movies_poll

= render 'form'

= link_to 'Show', @movies_poll
\|
= link_to 'Back', movies_polls_path

app/views/polls/index.html.haml
%h1 Listing movies_polls

%table
  %thead
    %tr
      %th Record
      %th
      %th
      %th

  %tbody
    - @movies_polls.each do |movies_poll|
      %tr
        %td= movies_poll.to_s
        %td= link_to fa_icon('eye'), movie_poll_path(movies_poll.omdb_item,movies_poll)
        %td= link_to fa_icon('pencil'), edit_movie_poll_path(movies_poll.omdb_item,movies_poll)
        %td= link_to fa_icon('trash'), movie_poll_path(movies_poll.omdb_item,movies_poll), method: :delete, data: { confirm: 'Are you sure?' }

app/views/polls/new.html.slim
.container.mt-4.px-0 style="background-image:url('#{url_for(@movie.banner)}'); height: 100%;color: white;background-size: cover; background-repeat:none;border-radius: 3rem;"
  .col style="background-color: rgba(0,0,0,0.6);padding: 2rem;border-radius: 3rem;"
    = link_to 'Back', movie_path(@movie)
    h1 = t('.title', movie_title: @movie.title)
    = render 'form'

app/views/polls/show.html.haml
%p#notice= notice

%p

= link_to 'Edit', edit_movie_poll_path(@movies_poll)
\|
= link_to 'Back', movie_polls_path